# -*- mode: ruby -*-
# vi: set ft=ruby :





Vagrant.configure(2) do |config|

    
    #Version de ubuntu a instalar

	config.vm.box = "ubuntu/xenial64"
    

    #Especificaciones de la maquina
	config.vm.provider "virtualbox" do |v|
        	    v.name = "DesServer"
            	v.memory = 8192
            	v.cpus = 2
            	v.gui = false
	end
   
    #Ejecutar install.sh
	config.vm.provision "install", type: "shell" do |s|
	   
	    s.path = "./scripts/install.sh"
        

	end

    #Ejecutar las siguientes lineas
    config.vm.provision "shell", inline: <<-SHELL
    
        yes "yes" | sudo apt-get update -q
        yes "yes" |sudo apt-get upgrade -q
        echo 'PATH="/usr/local/texlive/2014/bin/x86_64-linux:$PATH"'>> /home/vagrant/.bashrc
        echo 'PATH="$HOME/anaconda3/bin:$PATH"'>> /home/vagrant/.bashrc
        
        source /home/vagrant/.bashrc

        #setxkbmap -layout es
    SHELL

    #Ejecutar el script install2

    config.vm.provision "install2", type: "shell" do |s|
	   
	    s.path = "./scripts/install2.sh"
        

	end

end
