# -*- mode: ruby -*-
# vi: set ft=ruby :





Vagrant.configure(2) do |config|

	config.vm.box = "ubuntu/xenial64"
    #config.vm.box="continuumio/anaconda3"


	config.vm.provider "virtualbox" do |v|
        	    v.name = "DesServer"
            	v.memory = 8192
            	v.cpus = 2
            	v.gui = false
	end
   

	config.vm.provision "install", type: "shell" do |s|
	   
	    s.path = "./scripts/install.sh"
        

	end

    config.vm.provision "shell", inline: <<-SHELL
    
        yes "yes" | sudo apt-get update -q
        yes "yes" |sudo apt-get upgrade -q
        echo 'PATH="/usr/local/texlive/2014/bin/x86_64-linux:$PATH"'>> /home/vagrant/.bashrc
        echo 'PATH="$HOME/anaconda3/bin:$PATH"'>> /home/vagrant/.bashrc
        
        source /home/vagrant/.bashrc

        #setxkbmap -layout es
    SHELL

    	config.vm.provision "install2", type: "shell" do |s|
	   
	    s.path = "./scripts/install2.sh"
        

	    end

end
